language: php
php:
  - 7.1
  - 7.2

matrix:
  fast_finish: true

install:
  - composer self-update
  - composer install --no-interaction --prefer-source

script:
  - composer phpstan
  - composer phpcs
  - composer tests
